# -*- coding: utf-8 -*-
"""A1_Recursion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpMkaTLBl71p4MFP8Xj9F76IAoeOw3FT
"""

#Akshata Padalkar(anp178) U4A1
string = input("Provide a String: ").lower()
character = input("Provide a Character: ").lower()
count = 0
def counting(string,character):
  if string == "":
    return 0
  elif string[0] == character:
    return 1 + counting(string[1:], character)
  else:
    return counting(string[1:], character)

result = counting(string, character)
print(result)