# -*- coding: utf-8 -*-
"""A2-temperature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAhoPXb_AJNUk9qVKIKB45J7Bk6lJuK0
"""

#Akshata Padalkar U1A2
temp = int(input("What is the temperature(F)? "))
if(temp < 40):
  print("Wear a winter coat")
elif(temp >= 40 and temp <= 60):
  print("Wear a scarf")
else:
  print("Wear sunglasses")