# -*- coding: utf-8 -*-
"""A3_IsHarshad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H03bDeSNPKDJeNen9tv9ES3cX3Y4jqbH
"""

def isHarshad(num):
  digits = [int(d) for d in str(num)]
  total = sum(digits)
  if total == 0:
    return False
  if num % total == 0:
    return True
  else:
    return False

harshad_numbers = []

for n in range(1, 501):
  if isHarshad(n):
        harshad_numbers.append(n)
print(harshad_numbers)