# -*- coding: utf-8 -*-
"""AU6ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18993er8p7-FwiogqiNDm1FR9SElygNYn
"""

# Commented out IPython magic to ensure Python compatibility.
# #anp178 U6 a1
# #linkedln.py from class used as a base
# %%writefile updatedLinkedlist.py
# class Node(object):
# 
#     def __init__(self, data=None, nextNode=None):
#         self.data = data
#         self.nextNode = nextNode
# 
# class linkedList(object):
# 
#     def __init__(self, head=None):
#         self.head = head
#         self.size = 0
# 
#     def insert(self, node):
# 
#         if not self.head:
#             self.head = node
#             self.size += 1
#         else:
#             # set new nodes pointer to old head
#             node.nextNode = self.head
#             # reset head to new node
#             self.head = node
#             self.size +=1
# 
#     def getSize(self):
#         return self.size
# 
#     def printLL(self):
#         mynode = self.head
#         c = 0
#         while mynode:
#             c += 1
#             print(mynode.data, c)
#             mynode = mynode.nextNode
# 
# 
#     def getNum(self, n):
#       current = self.head
#       index = 1
# 
#       while current:
#         if index == n:
#           return current.data
#         current = current.nextNode
#         index += 1
# 
#       return None
# 
#

#from class usell.py
from updatedLinkedlist import *

MyList = linkedList()

MyList.insert(Node("Lars"))
MyList.insert(Node("Alex"))
print(MyList.getSize())
MyList.insert(Node("Michael"))
print(MyList.getSize())
MyList.insert(Node("Abhi"))

# Use my print method
MyList.printLL()
print("n\")
print(MyList.getNum(2))

