# -*- coding: utf-8 -*-
"""EC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXcMJPayQDcUhlLDTtxYKa2IfXw5a12f

Use Matplotlib to graph the data from Unit 4's Assignment 2.  Use two data sets, the rands.txt numbers sorted and then the same numbers unsorted.

Make this a line graph with index in list and the actual number as the X and the Y.

Screen shots of the two graphs (sorted and unsorted) and the code are the deliverables here.
"""

import matplotlib.pyplot as plt

def main():
  with open("rands.txt", "r") as f:
    raw = f.read()
  raw = raw.strip()
  raw = raw.replace('"', "")
  raw_list = raw.split()
  data_list = []
  for x in raw_list:
    num = int(x)
    data_list.append(num)

  x = list(range(len(data_list)))
  y = data_list

  plt.plot(x, y, color='green')
  plt.title("Unsorted: Index vs Value")
  plt.xlabel("Index")
  plt.ylabel("Value")

  plt.show()
main()

def main():
  with open("rands.txt", "r") as f:
    raw = f.read()
  raw = raw.strip()
  raw = raw.replace('"', "")
  raw_list = raw.split()
  data_list = []
  for x in raw_list:
    num = int(x)
    data_list.append(num)
  data_list.sort()

  x = list(range(len(data_list)))
  y = data_list

  plt.plot(x, y, color='blue')
  plt.title("Sorted: Index vs Value")
  plt.xlabel("Index")
  plt.ylabel("Value")

  plt.show()
main()

